Repository openfisca/openfisca-ops, pull requests merged in 2018-10, with the labels that each got.

#68 Use Python 3.7
  README.md
Labels: kind:documentation

#70 Serve demo over https
  README.md
  auto-update-ssl-certificates/README.md
  demo.openfisca.org/demo.openfisca.org.conf
  guides/Set-up-SSL.md
Labels: flow:team:doing, kind:devops

#71 Forward scheme to Flask apps
  demo.openfisca.org/demo.openfisca.org.conf
  demo.openfisca.org/legislation-explorer/.env
  fr.openfisca.org/fr.openfisca.org.conf
Labels: flow:team:doing
