Repository openfisca/openfisca-ops, pull requests merged in 2018-04, with the labels that each got.

#40 Add fr.openfisca.org/legislation
  CHANGELOG.md
  fr.openfisca.org/fr.openfisca.org.conf
  fr.openfisca.org/legislation-explorer/legislation-explorer.service
Labels: flow:team:doing, kind:devops

#41 Redirect old legislation-explorer
  CHANGELOG.md
  legislation.openfisca.fr/legislation.openfisca.fr.conf
Labels: flow:team:doing

#43 Serve fr.openfisca.org/api/v21
  CHANGELOG.md
  fr.openfisca.org/api/v21/deploy.sh
  fr.openfisca.org/api/v21/openfisca-web-api-fr21.service
  fr.openfisca.org/api/v21/requirements.txt
  fr.openfisca.org/fr.openfisca.org.conf
Labels: flow:team:doing

#37 Create an OpenFisca key pass
  README.md
  openfisca.kdbx
Labels: flow:team:doing

#34 Improve changelog structure and formatting
  CHANGELOG.md
Labels: flow:team:doing, kind:documentation

#44 Delete fr.openfisca.org deployment script
  CHANGELOG.md
  fr.openfisca.org/website/deploy.sh
Labels: flow:team:doing, kind:devops
